bases:
  - ../../../base/ops

resources:
  - certificate.yaml
  - elasticsearch.yaml
  - grafana-tls-secret.yaml

patchesStrategicMerge:
  - grafana-deployment-patch.yaml
  - grafana-ingress-patch.yaml
  - prometheus-prometheus-patch.yaml
  - haproxy-ingress-patch.yaml
